import React from 'react'
import Head from 'next/head'
import globe from '../images/globe.png'
import styles from './Layout.module.css'

const Layout = ({children}) => {
  return (
    <div>
      <Head>
        <title>Worlds Country Ranks</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className={styles.container}>
        <header className={styles.header}>
          <div><img src={globe} alt="" className={styles.globe} /></div>
          <p className={styles.title}>Worlds <br /> Country <br /> Ranks</p>
        </header>

        
        <main >
          {children}
        </main>
  
        <footer >
          footer
        </footer>
      </div>
    </div>
  )
}

export default Layout
